<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE high_street_gym [
  <!ELEMENT high_street_gym (#PCDATA)>
  <!ELEMENT user (user_id, first_name, last_name, username,admin,password)>
  <!ELEMENT user_id (#PCDATA)>
  <!ELEMENT first_name (#PCDATA)>
  <!ELEMENT last_name (#PCDATA)>
  <!ELEMENT username (#PCDATA)>
  <!ELEMENT admin (#PCDATA)>
  <!ELEMENT password (#PCDATA)>
]>
<high_street_gym>
  <user>
    <user_id>6</user_id>
    <first_name>John</first_name>
    <last_name>Doe</last_name>
    <username>Johnny</username>
    <admin>0</admin>
    <password>1234</password>
  </user>
</high_street_gym>